version: '3'
services:
  db:
    container_name: mangapie.mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mangapie
      MYSQL_USER: mangapie
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    container_name: mangapie.redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always

  web:
    container_name: mangapie.nginx
    image: mangapie.nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./php-fpm/run/php:/run/php
      - ./www/mangapie:/var/www/mangapie
      - ./nginx/log:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d/mangapie.conf:/etc/nginx/conf.d/mangapie.conf
    restart: always
    links:
      - php
    build:
      context: .
      dockerfile: mangapie.nginx.Dockerfile

  php:
    container_name: mangapie.php7-fpm
    image: mangapie.php7-fpm:latest
    environment:
      APP_DEBUG: "false"
      APP_URL: "https://192.168.1.142/"
      APP_IMAGE_EXTRACT: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mangapie
      DB_USERNAME: mangapie
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
      # php config
      - ./php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php-fpm/run/php:/run/php
      # mangapie
      - ./www/mangapie:/var/www/mangapie
      - ./mangapie.sh:/usr/local/bin/mangapie
      # Add your manga dirs here
      - ./manga:/manga:ro
    links:
      - db
      - redis
    build:
      context: .
      dockerfile: mangapie.php7-fpm.Dockerfile
    restart: always

  supervisor:
    container_name: mangapie.supervisor
    image: mangapie.supervisor:latest
    environment:
      APP_DEBUG: "false"
      APP_URL: "https://192.168.1.142/"
      APP_IMAGE_EXTRACT: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mangapie
      DB_USERNAME: mangapie
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
      - ./php-fpm/run/php:/run/php
      - ./www/mangapie:/var/www/mangapie
      - ./manga:/manga:ro
      - ./supervisor/conf.d/mangapie.conf:/etc/supervisor/conf.d/mangapie.conf
      - ./supervisor/log:/var/log/supervisor
    links:
      - db
      - redis
      - php
    build:
      context: .
      dockerfile: mangapie.supervisor.Dockerfile
